muss_study/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

from muss_study import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
    path('', include('shop.urls')),
    path('', include('reviews.urls')),
    path('', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('news/', news_index, name="news_index"),
    path('news/category/<int:category_id>/', get_category, name="news_category"),
    path('news/<int:news_id>/', view_news, name="view_news"),
    path('news/add_news/', add_news, name="add_news"),
    path('news/edit/<int:pk>/', login_required(UpdateNews.as_view()), name="edit_news"),
    path('news/remove/<int:pk>/', login_required(DeleteNews.as_view()), name="delete_news")
]

users/urls.py
from django.urls import path
from .views import *

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', user_login, name='user_login'),
    path('logout/', user_logout, name='user_logout'),
    path('settings/', profile_edit, name='profile_edit'),
    path('password-reset/', auth_views.PasswordResetView.as_view
         (template_name='users/password-reset.html'),
         name='password_reset'),
    path('password-reset-sent/', auth_views.PasswordResetDoneView.as_view
         (template_name='users/password-reset-sent.html'),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view
         (template_name='users/password-reset-form.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view
         (template_name='users/password-reset-complete.html'),
         name='password_reset_complete'),
    path('settings/password-change/', MyPasswordChangeView.as_view(), name='password_change'),
    path('settings/password-change/done/', MyPasswordResetDoneView.as_view(), name='password_reset_done_not_email'),
    path('<str:slug>/', ProfileView.as_view(), name='user_profile'),
    path('', home, name='home')
]

users/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save


class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE, verbose_name='Имя пользователя')
    date_of_birth = models.DateField(blank=True, null=True, verbose_name='Дата рождения')
    photo = models.ImageField(upload_to='users/%Y/%m/%d', default='images/nav/default_user.jpg', verbose_name='Фото')
    photo_background = models.ImageField(upload_to='users/%Y/%m/%d', default='images/nav/default_background.png',
                                         verbose_name='Задний фон')
    city = models.CharField(max_length=150, blank=True, null=True, verbose_name='Город')
    school = models.CharField(max_length=150, blank=True, null=True, verbose_name='Школа')
    vk_link = models.CharField(max_length=150, blank=True, null=True, verbose_name='Ссылка на вк')
    inst_link = models.CharField(max_length=150, blank=True, null=True, verbose_name='Ссылка на инсту')

    def __str__(self):
        return str(self.user)

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'


def create_profile(**kwargs):
    if kwargs['created']:
        Profile.objects.create(user=kwargs['instance'])


post_save.connect(create_profile, sender=User)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth.models import User

from users.models import Profile


class UserAuthenticationForm(AuthenticationForm):
    username = forms.CharField,
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'password__input'}))

    def __init__(self, *args, **kwargs):
        super(UserAuthenticationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget = forms.TextInput(attrs={'class': 'username__input'})


class CreateUserForm(UserCreationForm):
    username = forms.CharField(required=True, min_length=6, max_length=30)

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'register__input'}),
            'first_name': forms.TextInput(attrs={'class': 'first__name__input'}),
            'last_name': forms.TextInput(attrs={'class': 'first__name__input'})
        }

    def __init__(self, *args, **kwargs):
        super(CreateUserForm, self).__init__(*args, **kwargs)
        self.fields['password1'].widget = forms.PasswordInput(attrs={'class': 'register__input'})
        self.fields['password2'].widget = forms.PasswordInput(attrs={'class': 'register__input'})
        self.fields['username'].widget = forms.TextInput(attrs={'class': 'register__input'})

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError(f'Пользователь с таким именем уже существует.')
        return username

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError(f'Пользователь с таким почтовым адресом уже зарегистрирован.')
        return email

    def clean_password2(self):
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Пароли не совпадают.')
        return password2


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'settings__input'}),
            'first_name': forms.TextInput(attrs={'class': 'settings__input'}),
            'last_name': forms.TextInput(attrs={'class': 'settings__input'})
        }


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('date_of_birth', 'photo', 'photo_background', 'city', 'school',  'vk_link', 'inst_link')
        widgets = {
            'date_of_birth': forms.DateInput(attrs={'class': 'settings__input'}),
            'city': forms.TextInput(attrs={'class': 'settings__input'}),
            'school': forms.TextInput(attrs={'class': 'settings__input'}),
            'vk_link': forms.TextInput(attrs={'class': 'settings__input'}),
            'inst_link': forms.TextInput(attrs={'class': 'settings__input'}),
        }


class MyPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'new_password_input',
                                                                     'type': 'password'}))
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'new_password_input',
                                                                      'type': 'password'}))
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'new_password_input',
                                                                      'type': 'password'}))

    class Meta:
        model = User
        fields = ('old_password', 'new_password1', 'new_password2')

users/views.py
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.views import PasswordChangeView, PasswordResetDoneView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import DetailView

from .forms import CreateUserForm, UserAuthenticationForm, UserEditForm, ProfileEditForm, MyPasswordChangeForm


def home(request):
    return render(request, 'users/home.html')


def register(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, 'Аккаунт ' + user + ' успешно зарегистрирован!')
            return redirect('user_login')
    context = {'form': form}
    return render(request, 'users/register.html', context)


def user_login(request):
    if request.method == 'POST':
        form = UserAuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('user_profile', request.user.username)
        else:
            messages.info(request, 'Неверное имя пользователя или пароль!')
    else:
        form = UserAuthenticationForm()
    context = {'form': form}
    return render(request, 'users/login.html', context)


def user_logout(request):
    logout(request)
    return redirect('home')


class ProfileView(DetailView):
    model = User
    slug_field = 'username'
    template_name = "users/profile.html"


@login_required
def profile_edit(request):
    user_form = UserEditForm(instance=request.user)
    profile_form = ProfileEditForm(instance=request.user.profile)
    if request.method == "POST":
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile, data=request.POST, files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('user_profile', request.user.username)
    context = {'user_form': user_form, 'profile_form': profile_form}
    return render(request, 'users/settings.html', context)


class MyPasswordChangeView(PasswordChangeView):
    form_class = MyPasswordChangeForm
    template_name = "users/password-change.html"
    success_url = reverse_lazy('password_reset_done_not_email')


class MyPasswordResetDoneView(PasswordResetDoneView):
    template_name = "users/password-reset-done_not_email.html"

users/templates/users/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Главная
{% endblock %}
{% block content %}

{% endblock %}

users/templates/users/login.html
{% load static %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="{% static 'css/login/login.css' %}">
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600;700&display=swap" rel="stylesheet">
<title>Вход</title>
    <div class="login__container">
        <div class="login__block">
            <div class="login__logo">
                <p class="login__header">Войти на сайт</p>
            </div>
            <div class="login__or__register">
                <div class="login__or__register__block">
                    <a href="{% url 'user_login' %}" class="login">Войти</a>
                    <a href="{% url 'register' %}" class="register">Зарегистрироваться</a>
                </div>
            </div>
            <form method="POST" action="" class="form">
                {% csrf_token %}
                <div class="username__main__block">
                    <div class="username__block">
                        <p class="username">Имя пользователя</p>
                    </div>
                    <div class="username__input__block">
                        {{ form.username }}
                    </div>
                </div>
                <div class="password__main__block">
                    <div class="password__block">
                        <p class="password">Пароль</p>
                    </div>
                    <div class="password__input__block">
                        {{ form.password }}
                    </div>
                </div>
                <div class="problem__block">
                    <a href="{% url 'password_reset' %}" class="problem">Забыли пароль?</a>
                </div>
                <div class="login__btn__block">
                    <button type="submit" class="login__btn">Войти</button>
                </div>
            </form>
        </div>
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'info' %}
                        <div class="message__info__block">
                            <p class="message__info">{{ message }}</p>
                        </div>
                    {% else %}
                        <div class="message__success__block">
                            <p class="message__success">{{ message }}</p>
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
    </div>

users/templates/users/password-change.html
{% extends "base.html" %}

{% block title %}Новый пароль{% endblock %}

{% block content %}
    <div class="container">
        <div class="settings__main__block">
            <div class="settings__menu">
                <div class="settings__link__block1">
                    <a href="{% url 'profile_edit' %}" class="settings__link1">Редактировать профиль</a>
                </div>
                <div class="settings__link__block2">
                    <a href="{% url 'password_change' %}" class="settings__link2">Сменить пароль</a>
                </div>
            </div>
            <div class="change__password__block">
                <div class="new__password__inner">
                    <h1 class="new__password__title">Новый пароль</h1>
                    <h3 class="new__password__subtitle">Придумайте надежный пароль</h3>
                </div>
                <form action="" method="post">
                    <div class="new__password__text__block">
                        <div class="text__new__password__block">
                            <p class="text__new__password">Старый пароль:</p>
                        </div>
                        <div class="new__password__input__block">
                            {{ form.old_password }}
                        </div>
                    </div>
                    <div class="new__password__text__block1">
                        <div class="text__new__password__block1">
                            <p class="text__new__password">Новый пароль:</p>
                        </div>
                        <div class="new__password__input__block">
                            {{ form.new_password1 }}
                        </div>
                    </div>
                    <div class="new__password__text__block2">
                        <div class="text__new__password__block2">
                            <p class="text__new__password">Повторите пароль:</p>
                        </div>
                        <div class="new__password__input__block">
                            {{ form.new_password2 }}
                        </div>
                    </div>
                    <div class="button__password__change__block">
                        <input type="submit" value="Сохранить" class="button__password__change">
                    </div>
                    {% csrf_token %}
                </form>
            </div>
        </div>
        {% if form.errors %}
            {% if form.errors.old_password %}
                    <div class="errors__block1">
                        <p class="errors__text1">{{ form.errors.old_password.as_text|cut:"*" }}</p>
                    </div>
            {% endif %}
            {% if form.errors.new_password2 %}
                    <div class="errors__block1">
                        <p class="errors__text1">{{ form.errors.new_password2.as_text|cut:"*" }}</p>
                    </div>
            {% endif %}
        {% endif %}
    </div>
{% endblock %}

users/templates/users/password-reset-complete.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Восстановление пароля завершено
{% endblock %}
{% block content %}
    <div class="container">
        <div class="success__password__reset__main__block">
            <div class="new__password__inner">
                 <h1 class="success__new__password__title">Восстановление пароля завершено</h1>
                 <h3 class="success__new__password__subtitle2">Ваш пароль был сохранен. Теперь вы можете войти</h3>
             </div>
        </div>
    </div>
{% endblock %}

users/templates/users/password-reset-done_not_email.html
{% extends "base.html" %}

{% block title %}Пароль успешно изменен{% endblock %}

{% block content %}
    <div class="container">
        <div class="success__password__reset__main__block">
            <div class="new__password__inner">
                 <h1 class="success__new__password__title">Пароль успешно изменен</h1>
                 <h3 class="success__new__password__subtitle2">Ваш пароль был сохранен</h3>
             </div>
        </div>
    </div>
{% endblock %}

users/templates/users/password-reset-form.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Новый пароль
{% endblock %}
{% block content %}
    <div class="container">
        <div class="password__reset__main__block">
            <div class="new__password__inner">
                <h1 class="new__password__title">Новый пароль</h1>
                <h3 class="new__password__subtitle">Придумайте надежный пароль</h3>
            </div>
            <form action="" method="post">
                <div class="new__password__text__block1">
                    <div class="text__new__password__block1">
                        <p class="text__new__password">Новый пароль:</p>
                    </div>
                    <div class="new__password__input__block">
                        {{ form.new_password1 }}
                    </div>
                </div>
                <div class="new__password__text__block2">
                    <div class="text__new__password__block2">
                        <p class="text__new__password">Повторите пароль:</p>
                    </div>
                    <div class="new__password__input__block">
                        {{ form.new_password2 }}
                    </div>
                </div>
                <div class="button__password__change__block">
                     <p><input type="submit" value="Сохранить" class="button__password__change"></p>
                </div>
                {% csrf_token %}
            </form>
        </div>
        {% if form.errors %}
            {% if form.errors.new_password2 %}
                    <div class="errors__block1">
                        <p class="errors__text1">{{ form.errors.new_password2.as_text|cut:"*" }}</p>
                    </div>
            {% endif %}
        {% endif %}
    </div>
{% endblock %}

users/templates/users/password-reset-sent.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Письмо с инструкциями по восстановлению пароля отправлено
{% endblock %}
{% block content %}
    <div class="container">
        <div class="info__password__reset__main__block">
            <div class="new__password__inner">
                <h1 class="info__new__password__title">Письмо с инструкциями по восстановлению пароля отправлено</h1>
                <h3 class="info__new__password__subtitle2">Если вы не получили письмо, пожалуйста, убедитесь, что вы ввели адрес с которым вы зарегистрировались, и проверьте папку со спамом</h3>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/password-reset.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Восстановление пароля
{% endblock %}
{% block content %}
     <div class="container">
         <div class="password__reset__main__block">
             <div class="new__password__inner">
                 <h1 class="new__password__title">Восстановление пароля</h1>
                 <h3 class="new__password__subtitle1">Забыли пароль? Введите свой адрес электронной почты ниже, и мы вышлем вам инструкцию, как установить новый пароль</h3>
             </div>
             <form method="POST" action="">
                 {% csrf_token %}
                 <div class="email__text__block1">
                     <div class="email__setting__block1">
                         <p class="email__setting1">Электронный адрес:</p>
                     </div>
                     <div class="email__reset__block__input">
                         {{ form }}
                     </div>
                 </div>
                 <div class="button__password__change__block">
                     <p><input type="submit" value="Отправить" class="button__password__change"></p>
                 </div>
             </form>
         </div>
        {% if form.errors %}
            {% if form.errors.email %}
                    <div class="errors__block1">
                        <p class="errors__text1">{{ form.errors.email.as_text|cut:"*" }}</p>
                    </div>
            {% endif %}
        {% endif %}
     </div>
{% endblock %}

users/templates/users/settings.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Настройки
{% endblock %}
{% block content %}
    <div class="container">
        <div class="settings__main__block">
            <div class="settings__menu">
                <div class="settings__link__block2">
                    <a href="{% url 'profile_edit' %}" class="settings__link2">Редактировать профиль</a>
                </div>
                <div class="settings__link__block1">
                    <a href="{% url 'password_change' %}" class="settings__link1">Сменить пароль</a>
                </div>
            </div>
            <div class="settings__profile__main__block">
                <div class="new__password__inner">
                    <h1 class="new__password__title">Общедоступная информация</h1>
                    <h3 class="new__password__subtitle">Эта информация видна другим пользователям</h3>
                </div>
                <form id="setting-form" action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="setting__profile__photo__background__block">
                            <img src="{{ request.user.profile.photo_background.url }}" alt="" id="setting__profile__photo__background" class="setting__profile__photo__background">
                        <div class="file__block1255">
                            <label for="id_photo_background">
                                <svg xmlns="http://www.w3.org/2000/svg" class="change__profile__photo__svg" enable-background="new 0 0 512 512" viewBox="0 0 512 512"><g><path d="m467 121h-86.703l-11.177-55.883c-2.794-13.974-15.166-24.117-29.417-24.117h-167.406c-14.25 0-26.623 10.143-29.417 24.117l-11.177 55.883h-86.703c-24.813 0-45 20.187-45 45v260c0 24.813 20.187 45 45 45h422c24.813 0 45-20.187 45-45v-260c0-24.813-20.187-45-45-45zm-294.703-50h167.406l10 50h-187.406zm309.703 355c0 8.271-6.729 15-15 15h-422c-8.271 0-15-6.729-15-15v-260c0-8.271 6.729-15 15-15h422c8.271 0 15 6.729 15 15z"/><path d="m256 185c-61.206 0-111 49.794-111 111s49.794 111 111 111 111-49.794 111-111-49.794-111-111-111zm0 192c-44.664 0-81-36.337-81-81s36.336-81 81-81 81 36.337 81 81-36.336 81-81 81z"/><path d="m128 185h-48c-8.284 0-15 6.716-15 15s6.716 15 15 15h48c8.284 0 15-6.716 15-15s-6.716-15-15-15z"/></g></svg>
                            </label>
                            <input class="id_photo_background__input" onchange="readURL1(this);" type="file" name="photo_background" accept="image/*" id="id_photo_background">
                        </div>
                    </div>
                    <div id="imageBox1" class="setting__profile__photo__block">
                            <img src="{{ request.user.profile.photo.url }}" alt="" id="setting__profile__photo" class="setting__profile__photo">
                        <div class="file__block">
                            <label for="upload-photo-profile">
                                <svg xmlns="http://www.w3.org/2000/svg" class="change__profile__photo__svg" enable-background="new 0 0 512 512" viewBox="0 0 512 512"><g><path d="m467 121h-86.703l-11.177-55.883c-2.794-13.974-15.166-24.117-29.417-24.117h-167.406c-14.25 0-26.623 10.143-29.417 24.117l-11.177 55.883h-86.703c-24.813 0-45 20.187-45 45v260c0 24.813 20.187 45 45 45h422c24.813 0 45-20.187 45-45v-260c0-24.813-20.187-45-45-45zm-294.703-50h167.406l10 50h-187.406zm309.703 355c0 8.271-6.729 15-15 15h-422c-8.271 0-15-6.729-15-15v-260c0-8.271 6.729-15 15-15h422c8.271 0 15 6.729 15 15z"/><path d="m256 185c-61.206 0-111 49.794-111 111s49.794 111 111 111 111-49.794 111-111-49.794-111-111-111zm0 192c-44.664 0-81-36.337-81-81s36.336-81 81-81 81 36.337 81 81-36.336 81-81 81z"/><path d="m128 185h-48c-8.284 0-15 6.716-15 15s6.716 15 15 15h48c8.284 0 15-6.716 15-15s-6.716-15-15-15z"/></g></svg>
                            </label>
                            <input onchange="readURL(this);" class="settings__photo__input" type="file" name="photo" id="upload-photo-profile" accept="image/*"/>
                        </div>
                    </div>
                    <div id="progress-box" class="not-visible"></div>
                    <div class="first__name__text__block">
                        <div class="first__name__setting__block">
                            <p class="text__first__name__setting">Имя:</p>
                        </div>
                        <div class="name__setting__input__block">
                            {{ user_form.first_name }}
                        </div>
                    </div>
                    <div class="last__name__text__block">
                        <div class="last__name__setting__block">
                            <p class="last__name__name__setting">Фамилия:</p>
                        </div>
                        <div class="name__setting__input__block">
                            {{ user_form.last_name }}
                        </div>
                    </div>
                    <div class="date__of__birth__text__block">
                        <div class="date__of__birth__setting__block">
                            <p class="date__of__birth__name__setting">Дата рождения:</p>
                        </div>
                        <div class="name__setting__input__block">
                            {{ profile_form.date_of_birth }}
                        </div>
                    </div>
                    <div class="city__text__block">
                        <div class="city__setting__block">
                            <p class="last__name__name__setting">Город:</p>
                        </div>
                        <div class="name__setting__input__block">
                            {{ profile_form.city }}
                        </div>
                    </div>
                    <div class="school__text__block">
                        <div class="school__setting__block">
                            <p class="last__name__name__setting">Школа:</p>
                        </div>
                        <div class="name__setting__input__block">
                            {{ profile_form.school }}
                        </div>
                    </div>
                    <div class="inst__link__text__block">
                        <div class="inst__link__setting__block">
                            <p class="last__name__name__setting">Инстаграм:</p>
                        </div>
                        <div class="name__setting__input__block">
                            {{ profile_form.inst_link }}
                            <div class="vk__link__info__block">
                                <p class="vk__link__info">Ваше имя пользователя инстаграм</p>
                            </div>
                        </div>
                    </div>
                    <div class="vk__link__text__block">
                        <div class="vk__link__setting__block">
                            <p class="last__name__name__setting">Вконтакте:</p>
                        </div>
                        <div class="name__setting__input__block">
                            {{ profile_form.vk_link }}
                            <div class="vk__link__info__block">
                                <p class="vk__link__info">Ваше имя пользователя или id вконтакте</p>
                            </div>
                        </div>
                    </div>
                    <div class="new__password__inner1">
                        <h1 class="new__password__title">Личная информация</h1>
                        <h3 class="new__password__subtitle">Эти сведения не будут показываться в вашем общедоступном профиле</h3>
                    </div>
                    <div class="email__text__block">
                        <div class="email__setting__block">
                            <p class="email__setting">Эл. адрес:</p>
                        </div>
                        <div class="name__setting__input__block">
                            {{ user_form.email }}
                        </div>
                    </div>
                    <div class="button__password__change__block">
                        <input id="button__password__change" type="submit" value="Сохранить" class="button__password__change">
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}